services:
  gluetun:
    image: qmcgaw/gluetun
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${GLUETUN_DIR}:/gluetun

    
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      # OpenVPN:
      #- OPENVPN_USER=
      #- OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=${WG_PK}
      - FIREWALL_VPN_INPUT=${WG_FIREWALL}
      - WIREGUARD_ADDRESSES=${WG_ADR}
      - WIREGUARD_PRESHARED_KEY=${WG_PSK}
      # Timezone for accurate log times
      - TZ=Europe/Oslo
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      #- UPDATER_PERIOD=
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=1026
      - TZ=Europe/Oslo
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${QBT_CONFIG}:/config
      - ${QBT_DL}:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
    network_mode: service:gluetun #only change to QBT

    #networks:
    #  - proxy-net

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    devices:
      - dev/dri:dev/dri    
    container_name: jellyfin
    environment:
      - PUID=1026
      - PGID=1026
      - TZ=Europe/Oslo
      #- JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional

    #Volumes mapped to config and media
    volumes:
      - ${JELLY_CONFIG}:/config:shared
      - ${JELLY_SERIES}:/data/serier:shared
      - ${JELLY_FILMS}:/data/filmer:shared
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped

    #Defining the network to use
    networks:
      - proxy-net

#Using an external network shared with nginx proxy manager
networks:
  proxy-net:
    external: true


